# Generated by Django 4.2.5 on 2023-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
