# Generated by Django 4.2.5 on 2023-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_extra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Добавить в главное меню'),
        ),
        migrations.AlterField(
            model_name='service',
            name='extra_text',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. текст'),
        ),
    ]
