# Generated by Django 4.2.5 on 2023-09-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_main_alter_service_extra_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Название')),
                ('doc', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Документ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='app.service')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
