# Generated by Django 4.2.5 on 2023-09-25 09:50

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_documentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproduct',
            name='service',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='app.service'),
        ),
    ]
