# Generated by Django 4.2.5 on 2023-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_documentproduct_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentproduct',
            name='name',
            field=models.TextField(max_length=1000, verbose_name='Название'),
        ),
    ]
