# Generated by Django 4.2.5 on 2023-10-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
