# Generated by Django 4.2.5 on 2023-09-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='Дата')),
                ('start', models.TimeField(default='09:00:00', verbose_name='Начало записи')),
                ('end', models.TimeField(default='20:00:00', verbose_name='Конец записи')),
                ('step', models.IntegerField(default=20, verbose_name='Шаг записи, мин')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время записи')),
                ('name', models.TextField(blank=True, max_length=500, null=True, verbose_name='ФИО/Организация')),
                ('phone', models.TextField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.TextField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('automobile', models.TextField(blank=True, max_length=500, null=True, verbose_name='Автомобиль')),
                ('year', models.TextField(blank=True, max_length=100, null=True, verbose_name='Год выпуска')),
                ('reserve', models.BooleanField(default=False, verbose_name='Резерв')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='appointment.day', verbose_name='Число')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-day__day', 'time'],
            },
        ),
    ]
