# Generated by Django 4.2.5 on 2023-09-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-day__day', 'time'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Время'},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('time', 'day')},
        ),
    ]
