# Generated by Django 4.2.5 on 2023-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_entry_options_alter_entry_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='number',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Номер автомобиля'),
        ),
    ]
