# Generated by Django 4.2.5 on 2023-09-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_entry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='appointment.day', verbose_name='Число'),
        ),
    ]
