# Generated by Django 4.2.5 on 2023-09-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_entry_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='appointment.day', verbose_name='Число'),
        ),
    ]
