# Generated by Django 4.2.5 on 2023-09-22 08:51

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title', unique=True),
        ),
    ]
